apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test3
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "4"
    spec:
      containerConcurrency: 12
